apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: gitea
spec:
  title: Enterprise GTM Starter
  statusInformers:
    - deployment/enterprise-gtm-starter
  ports:
    - serviceName: "enterprise-gtm-starter"
      servicePort: 8888
      localPort: 8888
      applicationUrl: "http://enterprise-gtm-starter"
  icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSa6IpLT8VVWQDXoPuirydW6MC_BfKnuCOZA&usqp=CAU